### PR TITLE
RMBRE

### LINKED ISSUE #30: Walls - RMBRE
Add walls for maps in `RMBRE`

### PR DESCRIPTION
**Pull request by revilowaldow**
Closes #30 

A bit of an aside, I wouldn't mind an invitation to the project itself so I can move cards around etc.
I can close issues here (which auto closes them), or assign them to myself, but I can't move them to "in progress/review" as I pick up new ones.

### CODE REVIEW

**Review by TheGiddyLimit — APPROVED** [review]
added; didn't realise they were separate tbh

**Comment by revilowaldow** [comment]
No problem, all those PRs had both dm and player maps walled btw. And presume the new conflict on this is the index file. Will fix this evening.

**Comment by TheGiddyLimit** [comment]
all good; manually-walled player maps are fine, and probably slightly more accurate

and yes, the index file will have plenty conflicts. Trivial to resolve, though!

**Comment by revilowaldow** [comment]
Trivial to do in the web editor too as it turns out!

**Pull request merged**
